#!/usr/bin/bash

project=$(readlink -f "$(dirname "$0")")

set -e;

COMMANDS=(
  'set -e'
  '(composer install --quiet || composer update --quiet)'
  'cd /app'
  "/usr/local/lib/symbiont/bin/symbiont $*"
)

IFS=';'
docker run \
  --rm \
  -u "$(id -u "$USER"):$(id -g "$USER")" \
  -v "$PWD":/app:ro \
  -v "$project":/usr/local/lib/symbiont \
  -w /usr/local/lib/symbiont \
  -e "VERBOSE=${VERBOSE}" \
  -e "SYMBIONT_MODE=${MODE}" \
  --entrypoint bash \
  srcoder/development-php:php74-fpm \
  -c "${COMMANDS[*]}"
