name: PHP quality control

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  php:
    name: ${{ matrix.command }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        command:
          - phpcs
          - phpmd src,tests,lang ansi phpmd.xml.dist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP 7.4, Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, json, pcre
          tools: composer:v2

      - name: Install Composer package
        run: composer update

      - run: vendor/bin/${{ matrix.command }}
