name: PHP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  php:
    name: ${{ matrix.command }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        command:
          - phpcs
          - phpmd src,tests,lang ansi phpmd.xml.dist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP 7.4, Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, json, pcre
          tools: composer:v2

      - name: Install Composer package
        run: composer update

      - run: vendor/bin/${{ matrix.command }}


  phpunit:
    needs: [php]
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - windows-2019
          - macos-10.15
        php:
          - 7.4
          - 8.0
        composer:
          - 1
          - 2
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }}, PHP ${{ matrix.php }}, Composer ${{ matrix.composer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php }}, Composer ${{ matrix.composer }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, json, pcre
          tools: composer:v${{ matrix.composer }}

      - name: Install Composer package
        run: composer update

      - name: Run unit tests
        run: vendor/bin/phpunit tests
