name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - windows-2019
          - macos-10.15
        php:
          - 7.4
          - 8.0
        composer:
          - 1
          - 2
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }}, PHP ${{ matrix.php }}, Composer ${{ matrix.composer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php }}, Composer ${{ matrix.composer }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, json, pcre
          tools: composer:v${{ matrix.composer }}

      - name: Install Composer package
        run: composer update

      - name: Run unit tests
        run: vendor/bin/phpunit tests
