name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
        composer:
          - 1
          - 2
    runs-on: ubuntu-20.04
    name: PHPUnit @ PHP ${{ matrix.php }} using Composer V${{ matrix.composer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php }} and Composer ${{ matrix.composer }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, json, pcre
          tools: composer:v${{ matrix.composer }}

      - name: Install Composer package
        run: composer update

      - name: Run unit tests
        run: |
          vendor/bin/phpunit \
            --no-configuration \
            --bootstrap vendor/autoload.php \
            tests
