name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    strategy:
      matrix:
        php:
          - 7.4
    runs-on: ubuntu-20.04
    name: PHPUnit @ ${{ matrix.php }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, json, pcre
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: php-actions/phpunit@v9
        with:
          bootstrap: vendor/autoload.php
